services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bigdata_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d

